name: Update Hashes
on:
  workflow_dispatch:
  push:
    paths:
      - 'strategy-*.txt'
      - 'list-*.txt'

jobs:
  update-hashes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Calculate SHA256 hashes
      run: |
        for file in strategy-*.txt list-*.txt; do
          if [ -f "$file" ]; then
            case "$file" in
              strategy-*)
                echo "$file,$(sha256sum "$file" | awk '{print $1}')" >> hashes_strategies.csv
                ;;
              list-*)
                echo "$file,$(sha256sum "$file" | awk '{print $1}')" >> hashes_hosts.csv
                ;;
            esac
          fi
        done

        process_json() {
          local csv_file=$1
          local json_file=$2
          [ -f "$csv_file" ] || return 0
          
          jq -Rn --slurpfile json "$json_file" '
            [$json[0][] | {key: .name, value: .hash}] | from_entries as $old |
            [inputs | split(",") | {key: .[0], value: .[1]}] | from_entries as $new |
            $json[0] | map(.hash = ($new[.name] // .hash))
          ' "$csv_file" > updated.json
          mv updated.json "$json_file"
        }

        process_json hashes_strategies.csv strategies.json
        process_json hashes_hosts.csv hosts.json

        rm -f hashes_*.csv

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Автообновление хэшей стратегий и листов"
        file_pattern: |
          strategies.json
          hosts.json
